server:
  port: ${PORT:8080}

spring:
  application:
    name: zuulserver

zuul:
  prefix: /api
  addProxyHeaders: true
  forceOriginalQueryStringEncoding: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  connect-timeout-millis: 60000
  host.max-per-route-connections: 10000
  host.max-total-connections: 5000
  host.socket-timeout-millis: 60000

  semaphore:
    max-semaphores: 500
  ribbon:
    eager-load.enabled: true

  routes:
    authentication:
      path: /v1/user/oauth/token
      serviceId: SPRING-CLOUD-USER-API
      stripPrefix: true

    users:
      path: /service-user/**
  #    url: http://localhost:8080/v1/user
      serviceId: SPRING-CLOUD-USER-API
      stripPrefix: true

    travels:
      path: /service-travel/**
      serviceId: SPRING-CLOUD-TRAVEL-API
      stripPrefix: true

    vouchers:
      path: /service-voucher/**
      serviceId: SPRING-CLOUD-VOUCHER-API
      stripPrefix: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

eureka:
  instance:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
        thread:
          timeoutInMilliseconds: 40000


ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000