server:
  port: ${PORT:8080}
  name: zull-server

  ssl:
    enabled: true
    #key-alias: transtour-api
    key-store-type: jks
    key-store: /opt/app/keystore.jks
    key-password: transtour-api
    key-store-password: transtour-api

spring:
  application:
    name: zuul-server

zuul:
  prefix: /api
  addProxyHeaders: true
  forceOriginalQueryStringEncoding: true
  ignoreSecurityHeaders: true
  sensitiveHeaders: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin, Authorization
  connect-timeout-millis: 60000
  host.max-per-route-connections: 10000
  host.max-total-connections: 5000
  host.socket-timeout-millis: 60000
  sslHostnameValidationEnabled: false
  okhttp:
    enabled: true
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'

  semaphore:
    max-semaphores: 500
  ribbon:
    eager-load.enabled: true

  routes:

    users:
      path: /service-user/**
      serviceId: SPRING-CLOUD-USER-API
      stripPrefix: true

    travels:
      path: /service-travel/**
      serviceId: SPRING-CLOUD-TRAVEL-API
      stripPrefix: true

    notifications:
      path: /service-notification/**
      serviceId: SPRING-CLOUD-NOTIFICATION
      stripPrefix: true

    vouchers:
      path: /service-voucher/**
      serviceId: SPRING-CLOUD-VOUCHER-API
      stripPrefix: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

eureka:
  registerWithEureka: true
  fetchRegistry: true
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8080
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
        thread:
          timeoutInMilliseconds: 40000


ribbon:
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000000
  ConnectTimeout: 5000000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
  IsHostnameValidationRequired: false
  TrustStore: /opt/app/keystore.jks
  TrustStorePassword : transtour-api


  logging:
    file: /opt/app/zuul.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      com.aurora.core: DEBUG
      org.hibernate: ERROR


secret:
  key: key
