server:
  port: ${PORT:8080}
  name: zull-server

  ssl:
    enabled: true
    key-store: /opt/app/keystore.jks
    key-store-password: transtour-api

spring:
  application:
    name: zuul-server

zuul:
  prefix: /api
  addProxyHeaders: true
  forceOriginalQueryStringEncoding: true
  ignoreSecurityHeaders: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  connect-timeout-millis: 60000
  host.max-per-route-connections: 10000
  host.max-total-connections: 5000
  host.socket-timeout-millis: 60000

  semaphore:
    max-semaphores: 500
  ribbon:
    eager-load.enabled: true

  routes:
    authentication:
      path: /v1/user/oauth/token
      serviceId: SPRING-CLOUD-USER-API
      stripPrefix: true

    users:
      path: /service-user/**
  #    url: http://localhost:8080/v1/user
      serviceId: SPRING-CLOUD-USER-API
      stripPrefix: true

    travels:
      path: /service-travel/**
      serviceId: SPRING-CLOUD-TRAVEL-API
      stripPrefix: true

    notifications:
      path: /service-notification/**
      serviceId: SPRING-CLOUD-NOTIFICATION
      stripPrefix: true

    vouchers:
      path: /service-voucher/**
      serviceId: SPRING-CLOUD-VOUCHER-API
      stripPrefix: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

eureka:
  registerWithEureka: true
  fetchRegistry: true
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 8080
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
        thread:
          timeoutInMilliseconds: 40000


ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000